typography_spectrum: 0.6192393209785223
color:
  brandStrength: 0.8273271974176168
  lightness: 0.682966020423919
  saturation: 0.8680564188398421
  rhythmicContrast: 0.9850064786151052
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
layout_spectrum: 0.2586533713620156
name: Paragon Custom Homes Packages-Kits
navigation:
  - name: Home Packages
    url: 'http://www.paragonhomes.ca/custom-home-construction-packages.php'
    type: external
  - name: Details of Kit Inclusions
    url: >-
      http://cdn.maisonparagon.ca/administration/ckeditor/ckfinder/userfiles/files/Kit%20Details%20EN%20Feb15.PDF
    type: external
  - name: R-32 Wall System
    url: >-
      http://cdn.maisonparagon.ca/administration/ckeditor/ckfinder/userfiles/files/R32%20Wall%20En%20Mar14_13.png
    type: external
  - name: 'What’s the Difference? '
    url: >-
      http://cdn.maisonparagon.ca/administration/ckeditor/ckfinder/userfiles/files/What's%20the%20Difference%20R3.pdf
    type: external
title: Home Packages
description: Since 1988
