typography_spectrum: 0.6192393209785223
color:
  brandStrength: 0.8273271974176168
  lightness: 0.682966020423919
  saturation: 0.8680564188398421
  rhythmicContrast: 0.9850064786151052
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
layout_spectrum: 0.2586533713620156
name: Paragon Custom Homes Packages-Kits
navigation:
  - name: Home Packages
    url: 'http://www.paragonhomes.ca/custom-home-construction-packages.php'
    type: external
  - name: Details of Kit Inclusions
    url: >-
      http://cdn.maisonparagon.ca/administration/ckeditor/ckfinder/userfiles/files/Kit%20Details%20EN%20Feb15.PDF
    type: external
title: Home Packages
description: Since 1988
